 IF OBJECT_ID('CHKLUONGNV') IS NOT NULL
    DROP TRIGGER CHKLUONGNV
 GO
 CREATE TRIGGER CHKLUONGNV
    ON NHANVIEN FOR INSERT
AS
  IF(SELECT LUONG FROM INSERTED) <15000
     BEGIN 
	    PRINT N'L??NG PH?I L?N H?N 15000'
		ROLLBACK TRAN
	 END
--CHÈN
------CHÈN L?I
INSERT INTO NHANVIEN VALUES ('B','B','B','00','1977','HN','NAM',3000,'005',6)

------CHÈN THÀNH CÔNG
INSERT INTO NHANVIEN VALUES ('B','B','B','00','1977','HN','NAM',30000,'005',6)


SELECT * FROM NHANVIEN
WHERE MANV LIKE '00%'



/*b. Vi?t m?t hàm có các tham s? ??u vào t??ng ?ng v?i t?t c? các c?t c?a b?ng
NGUOIDUNG. Hàm này tr? v? mã ng??i dùng (giá tr? c?a c?t khóa chính c?a b?ng
NGUOIDUNG) th?a mãn các giá tr? ???c truy?n vào tham s?.*/
  
    IF OBJECT_ID('FNND')IS NOT NULL
	  DROP FUNCTION FNND
	GO
	CREATE FUNCTION FNND
	(
	   @TENND NVARCHAR(50), @GIOITINH NVARCHAR(5), @DIENTHOAI VARCHAR(15),
	   @DIACHI NVARCHAR(50), @QUAN NVARCHAR(50), @EMAIL VARCHAR(50)
	)
	RETURNS VARCHAR(10)
	BEGIN 
	  RETURN (SELECT MAND FROM NGUOIDUNG
	          WHERE HOTENND = @TENND
			  AND GIOITINH = @GIOITINH
			  AND SDT = @DIENTHOAI
			  AND DIACHI = @DIACHI
			  AND QUAN = @QUAN
			  AND EMAIL = @EMAIL)
	END
----G?I
DECLARE @MAND VARCHAR(10)
SET @MAND = DBO.FNND(N'Bùi Quang Hi?u',N'Nam','0395962002',N'??i M?ch',N'?ông Anh','hieubq')
SELECT @MAND AS MAND

	SELECT * FROM NGUOIDUNG

/*c. Vi?t m?t hàm có tham s? ??u vào là mã nhà tr? (c?t khóa chính c?a b?ng
NHATRO). Hàm này tr? v? t?ng s? LIKE và DISLIKE c?a nhà tr? này.*/

IF OBJECT_ID('FNTKE')IS NOT NULL
	  DROP FUNCTION FNTKE
GO
CREATE FUNCTION FNTKE
(
   @MANT VARCHAR(10)
)
RETURNS @THONGKE TABLE
       ([LIKE] INT, [DISLIKE] INT)
BEGIN
    ---CÂU L?NH SQL
    --T?NG S? L??NG
	DECLARE @SL INT
	SET @SL = (SELECT COUNT(*) FROM DANHGIA
	           WHERE MANT = @MANT)
	--LIKE HO?C DISLIKE
	DECLARE @LIKE INT
	SET @LIKE = (SELECT COUNT(*) FROM DANHGIA
	           WHERE MANT = @MANT AND [LIKE/DISLIKE] ='1')
	--HI?N TH? RA MÀN HÌNH T?NG LIKE VÀ DISLIKE
	INSERT @THONGKE VALUES (@LIKE, @SL - @LIKE)
	RETURN
END

---DEMO
 SELECT * FROM FNTKE('13')

SELECT * FROM DANHGIA

/*d. T?o m?t View l?u thông tin c?a TOP 10 nhà tr? có s? ng??i dùng LIKE nhi?u nh?t
g?m các thông tin sau:
- Di?n tích
- Giá
- Mô t?
- Ngày ??ng tin
- Tên ng??i liên h?
- ??a ch?
- ?i?n tho?i
- Email
*/
   IF OBJECT_ID('TOP10') IS NOT NULL
       DROP VIEW TOP10
   GO
   CREATE VIEW TOP10
   AS
     SELECT TOP 3 DIENTICH, GIAPHONG, MOTA, NGAYDANGTIN, HOTENND, NGUOIDUNG.DIACHI, 
	 SDT, EMAIL, COUNT([LIKE/DISLIKE]) AS LIKEMAX
	 FROM NHATRO JOIN DANHGIA ON NHATRO.MANT = DANHGIA.MANT
	             JOIN NGUOIDUNG ON NGUOIDUNG.MAND = DANHGIA.MAND
		WHERE [LIKE/DISLIKE]=1
	GROUP BY DIENTICH, GIAPHONG, MOTA, NGAYDANGTIN, HOTENND, NGUOIDUNG.DIACHI, 
	 SDT, EMAIL
	ORDER BY LIKEMAX DESC
	---G?I
	SELECT * FROM TOP10