--BÀi 1:
DECLARE @TL INT
SELECT @TL = SUM(LUONG)
FROM NHANVIEN
SELECT CAST(@TL AS INT) AS CA
SELECT CONVERT(INT, @TL) AS CO

--BÀI 2:
DECLARE @THONGTIN TABLE (MANV VARCHAR(10), TONGNT INT)
INSERT INTO @THONGTIN
SELECT MANV, COUNT(TENTN)
FROM dbo.NHANVIEN LEFT OUTER JOIN dbo.THANNHAN ON THANNHAN.MA_NVIEN = NHANVIEN.MANV
GROUP BY MANV
SELECT * FROM @THONGTIN
SELECT A.MaNV, UPPER(LEFT(TENNV,1))+RIGHT(TENNV,LEN(TENNV)-1) AS TEN,
CONVERT(NVARCHAR,NGSINH,105) AS NGAYSINH,
DATEDIFF(YEAR,NGSINH,GETDATE()) AS TUOI,
TONGNT
FROM NHANVIEN A INNER JOIN @thongTin B on A.MANV = B.MaNV



--BÀI 3:
DECLARE @BT3 TABLE
(SL INT, TENTRP NVARCHAR(20), NGAYNHAN DATE)
INSERT INTO @BT3
SELECT COUNT(MANV), TENPHG, CONVERT(NVARCHAR, NG_NHANCHUC, 105)
FROM NHANVIEN INNER JOIN PHONGBAN ON NHANVIEN.MANV = PHONGBAN.MAPHG
GROUP BY TENPHG, NG_NHANCHUC
SELECT * FROM @BT3
 
