CREATE DATABASE QLD
GO

CREATE TABLE VANPHONG
(
MAVP VARCHAR(10) NOT NULL,
TENVP NVARCHAR (50) NULL,
DIENTHOAI VARCHAR(10) NULL,
EMAIL NVARCHAR(50) NULL,
TRUONGPHONG NVARCHAR(50) NULL
PRIMARY KEY (MAVP),
)
GO

CREATE TABLE BDS
(
MABDS VARCHAR(10) NOT NULL,
TENBDS NVARCHAR (50) NULL,
DIACHI NVARCHAR(50) NULL,
MACSH VARCHAR(10) NULL,
MAVP VARCHAR(10) NULL
CONSTRAINT PK_BDS PRIMARY KEY (MABDS),
CONSTRAINT FK_MABDS_VANPHONG FOREIGN KEY(MAVP) REFERENCES VANPHONG
)
GO



INSERT [dbo].VANPHONG([MAVP], [TENVP], [DIENTHOAI],[EMAIL],[TRUONGPHONG]) VALUES ('VP1', N'NHÂN S?', '0324718945','VP1@GMAIL.COM',N'NGUYEN VAN A')
INSERT [dbo].VANPHONG([MAVP], [TENVP], [DIENTHOAI],[EMAIL],[TRUONGPHONG]) VALUES ('VP2', N'HÀNH CHÍNH', '0323748267','VP2@GMAIL.COM',N'NGUYEN VAN B')


INSERT [dbo].BDS([MABDS], [TENBDS], [DIACHI],[MACSH],[MAVP]) VALUES ('BDS1', N'CÁ NHÂN', N'THANH XUÂN','CSH1', 'VP1')
INSERT [dbo].BDS([MABDS], [TENBDS], [DIACHI],[MACSH],[MAVP]) VALUES ('BDS2', N'DOANH NGHI?P', N'??NG ?A','CSH2', 'VP1')


--BÀI 2
IF OBJECT_ID('B2') IS NOT NULL
DROP PROC B2
GO
CREATE PROC B2
@MAVP VARCHAR(10),
@TENVP NVARCHAR(50),
@DIENTHOAI VARCHAR(10),
@EMAIL VARCHAR(50),
@TRUONGPHONG NVARCHAR(50) 

AS 
IF @MAVP IS NULL OR @TENVP IS NULL OR @DIENTHOAI IS NULL OR @EMAIL IS NULL OR @TRUONGPHONG IS NULL
PRINT N' D? LI?U KHÔNG H?P L? '

ELSE
INSERT VANPHONG VALUES(@MAVP,@TENVP,@DIENTHOAI,@EMAIL,@TRUONGPHONG)
PRINT N'G?I THÀNH CÔNG'

-----G?I TH?T B?I
EXEC B2'VP1',N'PHÒNG HÀNH CHÍNH','0395962002',NULL,N'BÙI QUANG HI?U'
---G?I THÀNH CÔNG
EXEC B2'VP1',N'PHÒNG HÀNH CHÍNH','0395962002','HIEUBQPH13812@GMAIL.COM',N'BUI QUANG HI?U'
SELECT *FROM VANPHONG


--BÀI 3
IF OBJECT_ID('B3') IS NOT NULL
  DROP PROC B3
GO
  CREATE PROC B3
         @MAVP VARCHAR(10)
	AS
	 SELECT VANPHONG.MAVP, TENVP, TENBDS, DIACHI
	 FROM VANPHONG JOIN BDS ON VANPHONG.MAVP = BDS.MAVP
	 WHERE VANPHONG.MAVP = @MAVP

EXEC B3 'VP1'


--BÀI 4
IF OBJECT_ID('B4') IS NOT NULL
  DROP PROC B4
GO
  CREATE PROC B4
        @MAVP VARCHAR(10)
AS
  IF @MAVP IS NULL
  PRINT N'DU LIEU NHAP VAO KHONG HOP LE'
  
  ELSE
   DELETE FROM VANPHONG 
   DELETE FROM BDS
   WHERE MAVP = @MAVP
   PRINT N'XÓA THÀNH CÔNG'

EXEC B4 'VP1'

   SELECT * FROM VANPHONG

  
  --BÀI 5:
  IF OBJECT_ID('B5') IS NOT NULL
       DROP VIEW B5
   GO
   CREATE VIEW B5
   AS
     SELECT TOP 1 MABDS, TENBDS, DIACHI, MACSH, MAVP
	 FROM BDS 
	GROUP BY MABDS, TENBDS, DIACHI, MACSH, MAVP

	--G?I
	SELECT * FROM B5