--BÀI 1:

SELECT * FROM NHANVIEN
SELECT * FROM CONGVIEC
SELECT * FROM PHANCONG

SELECT TENDEAN, SUM(THOIGIAN) AS TONGGIO, 
CAST(SUM(THOIGIAN) AS DECIMAL (8,2)) AS DEC,
CONVERT(DECIMAL(8,2), SUM(THOIGIAN)) AS DEC,

CAST(SUM(THOIGIAN) AS VARCHAR) AS VAR,
CONVERT(VARCHAR, SUM(THOIGIAN)) AS VAR
FROM DEAN JOIN CONGVIEC ON DEAN.MADA = CONGVIEC.MADA
JOIN PHANCONG ON PHANCONG.MADA = CONGVIEC.MADA
GROUP BY TENDEAN



DECLARE @LTB VARCHAR (20)
SELECT @LTB = CONVERT(VARCHAR, AVG(LUONG), 1)
FROM NHANVIEN
GROUP BY PHG
--TRUY XUẤT
SELECT TENPHG, CONVERT(DECIMAL(8,2), AVG(LUONG), 1) AS DEC,
                REPLACE(LEFT(@LTB, LEN(@LTB)-3),'.',',') + '.'+ RIGHT(@LTB,2) AS VAR
FROM PHONGBAN JOIN NHANVIEN ON PHONGBAN.MAPHG = NHANVIEN.PHG
GROUP BY TENPHG



--BÀI 2:

SELECT TENDEAN, SUM(THOIGIAN) AS TONGGIO,
   CEILING(SUM(THOIGIAN)) AS CEI,
    FLOOR(SUM(THOIGIAN)) AS FLO,
	 ROUND(SUM(THOIGIAN),2) AS ROU
FROM DEAN JOIN CONGVIEC ON DEAN.MADA = CONGVIEC.MADA
JOIN PHANCONG ON PHANCONG.MADA = CONGVIEC.MADA
GROUP BY TENDEAN

   DECLARE @LTB FLOAT
   SELECT @LTB = AVG(LUONG)
   FROM NHANVIEN JOIN PHONGBAN ON NHANVIEN.PHG = PHONGBAN.MAPHG
   WHERE TENPHG = N'NGHIÊN CỨU'
   SELECT @LTB
   --XUẤT
   SELECT HONV, TENLOT, TENNV 
   FROM NHANVIEN 
   WHERE LUONG > @LTB


   --BÀI 3:

   SELECT HONV, TENLOT, TENNV, DCHI,
      UPPER(HONV) AS UPP, LOWER(TENLOT) AS LOW,
	  LOWER(LEFT(TENNV,1)) + UPPER (SUBSTRING(TENNV, 2,1))+ LOWER(RIGHT(TENNV, LEN(TENNV) -2)) AS SUB,
	  SUBSTRING(DCHI, CHARINDEX(' ',DCHI)+1, CHARINDEX(',',DCHI)- CHARINDEX(' ',DCHI)-1) AS CHAR

   FROM NHANVIEN



   SELECT DISTINCT HONV + ' ' + TENLOT+ ' ' + TENNV AS TRPHONG, TENPHG, TRPHG AS FPOLY
   FROM NHANVIEN JOIN PHONGBAN ON NHANVIEN.MANV = PHONGBAN.TRPHG
   WHERE TRPHG = (SELECT TRPHG FROM  NHANVIEN JOIN PHONGBAN ON NHANVIEN.PHG = PHONGBAN.MAPHG
                  GROUP BY TRPHG
				  HAVING COUNT (MANV) = (SELECT MAX(SLNN) 
				                         FROM (SELECT COUNT(MANV) AS SLNN
										      FROM NHANVIEN
											  GROUP BY PHG) AS SLNN))