CREATE DATABASE DANGKYHOC
GO
USE DANGKYHOC
GO
IF OBJECT_ID('SINHVIEN') IS NOT NULL
DROP TABLE SINHVIEN
GO
CREATE TABLE SINHVIEN
(
MASV VARCHAR(10) NOT NULL,
HOTEN NVARCHAR(50) NULL,
GIOITINH NVARCHAR(50)NULL,
DIACHI NVARCHAR(50)NULL,
SDT VARCHAR(15)NULL
CONSTRAINT PK_SINHVIEN PRIMARY KEY(MASV)
)
GO
IF OBJECT_ID('MONHOC') IS NOT NULL
DROP TABLE MONHOC 
GO
CREATE TABLE MONHOC
(
MAMH VARCHAR(10)NOT NULL,
TENMH NVARCHAR(50)NULL,
STCHI INT NULL
CONSTRAINT PK_MONHOC PRIMARY KEY(MAMH)
)
GO
IF OBJECT_ID('DANGKY') IS NOT NULL
DROP TABLE DANGKY
GO
CREATE TABLE DANGKY
(
MASV VARCHAR(10)NOT NULL,
MAMH VARCHAR(10)NOT NULL,
NGAYDK DATETIME NULL,
HOCKY INT NULL
CONSTRAINT FK_DANGKY_SINHVIEN FOREIGN KEY(MASV) REFERENCES SINHVIEN,
CONSTRAINT FK_DANGKY_MONHOC FOREIGN KEY(MAMH) REFERENCES MONHOC,
CONSTRAINT PK_DANGKY PRIMARY KEY(MASV,MAMH)
)
GO

----CAU2
IF OBJECT_ID('CAU2_1') IS NOT NULL
DROP PROC CAU2_1
GO
CREATE PROC CAU2_1
@MASV VARCHAR(10) ,
@HOTEN NVARCHAR(50),
@GIOITINH NVARCHAR(50),
@DIACHI NVARCHAR(50),
@SDT VARCHAR(15)
AS
IF @MASV IS NULL OR @GIOITINH IS NULL OR @DIACHI IS NULL OR @SDT IS NULL OR @HOTEN IS NULL
PRINT N' ?I?N CÒN THI?U'
ELSE
INSERT INTO SINHVIEN VALUES(@MASV,@HOTEN,@GIOITINH,@DIACHI,@SDT)
----GOI
GO
EXEC CAU2_1 'PH13911',N'LÃ V?N TH?','NAM',N'H?I PHÒNG','0323333211'
EXEC CAU2_1 'PH13912',N'NH?T LÊ',N'N?',N'H?I PHÒNG','0323333201'
EXEC CAU2_1 'PH13913',N'HI?U BÙI','NAM',N'H?I PHÒNG','0323333211'

------
IF OBJECT_ID('CAU2_2') IS NOT NULL
DROP PROC CAU2_2
GO
CREATE PROC CAU2_2
@MAMH VARCHAR(10),
@TENMH NVARCHAR(50),
@STCHI INT
AS 
IF @MAMH IS NULL OR @TENMH IS NULL OR @STCHI IS NULL
PRINT N' ?I?N THI?U'
ELSE
INSERT INTO MONHOC VALUES(@MAMH,@TENMH,@STCHI)
----
GO
EXEC CAU2_2 'MH01','ANH',15
EXEC CAU2_2 'MH02',N'V?N',16
EXEC CAU2_2 'MH03',N'HÓA',11
-------------
IF OBJECT_ID('CAU2_3') IS NOT NULL
DROP PROC CAU2_3
GO
CREATE PROC CAU2_3
@MASV VARCHAR(10),
@MAMH VARCHAR(10),
@NGAYDK DATETIME ,
@HOCKY INT NULL
AS
IF @MASV IS NULL OR @MAMH IS NULL OR @NGAYDK IS NULL OR @HOCKY IS NULL
PRINT N'?I?N THI?U'
ELSE
INSERT INTO DANGKY VALUES(@MASV,@MAMH,@NGAYDK,@HOCKY)
------
GO
EXEC CAU2_3 'PH13911','MH01','8/9/2021',3
EXEC CAU2_3 'PH13912','MH02','8/10/2021',3
EXEC CAU2_3 'PH13913','MH03','8/5/2021',3
SELECT*FROM DANGKY
-------CAU 4
IF OBJECT_ID('CAU4') IS NOT NULL
DROP VIEW CAU4
GO
CREATE VIEW CAU4
AS 
SELECT TOP 2 SINHVIEN.MASV,HOTEN,DIACHI,SDT,MONHOC.MAMH,TENMH,NGAYDK,HOCKY
FROM DANGKY INNER JOIN MONHOC ON DANGKY.MAMH=MONHOC.MAMH JOIN SINHVIEN ON DANGKY.MASV=SINHVIEN.MASV
ORDER BY NGAYDK DESC
GO
SELECT *FROM CAU4

-----------CAU5
------
IF OBJECT_ID('SPXOANV') IS NOT NULL
 DROP PROC SPXOANV
GO
CREATE PROC SPXOANV
 @NGAYDK DATETIME
AS 
 BEGIN TRY
  BEGIN TRAN 
   DECLARE @BANG TABLE
    (MASV VARCHAR(10), MAMH VARCHAR(10),NGAYDK DATETIME)
   INSERT @BANG SELECT SINHVIEN.MASV, MONHOC.MAMH,NGAYDK 
      FROM SINHVIEN JOIN DANGKY ON SINHVIEN.MASV=DANGKY.MASV 
	  JOIN MONHOC ON MONHOC.MAMH=DANGKY.MAMH
   DELETE DANGKY
   WHERE NGAYDK = ( SELECT NGAYDK FROM @BANG 
       WHERE NGAYDK = @NGAYDK)
   DELETE SINHVIEN
   WHERE MASV = ( SELECT MASV FROM @BANG 
       WHERE NGAYDK = @NGAYDK)
	   DELETE MONHOC
	   WHERE MAMH=( SELECT MAMH FROM @BANG 
       WHERE NGAYDK = @NGAYDK)
  COMMIT TRAN
 END TRY
 BEGIN CATCH
  ROLLBACK TRAN 
 END CATCH
GO
EXEC SPXOANV '8/10/2021'
SELECT *FROM SINHVIEN
SELECT*FROM MONHOC
SELECT *FROM DANGKY