--BÀI 1: 
  --CHO BIẾT LƯƠNG TRUNG BÌNH CỦA NHÂN VIÊN PHÒNG NGHIÊN CỨU
   DECLARE @LTB FLOAT
   SELECT @LTB = AVG(LUONG)
   FROM NHANVIEN JOIN PHONGBAN ON NHANVIEN.PHG = PHONGBAN.MAPHG
   WHERE TENPHG = N'NGHIÊN CỨU'
   SELECT @LTB AS LTB_PNC

   --BÀI2 :
   -- VIẾT CHƯƠNG TRÌNH TÌM UCLN CỦA 2 SỐ
   DECLARE @A INT, @B INT, @C INT
   SET @A = 12
   SET @B = 5
   SET @C = 0
   WHILE (@A != @B)
   BEGIN IF(@A > @B) 
   SET @A = @A - @B
   ELSE
   SET @B = @B - @A
   END
   SET @C = @A
   SET @C = @B
   SELECT @C AS UCLN
   

   --BÀI 3 :
   --TẠO BIẾN BẢNG CHỨ THÔNG TIN CÁC NHÂN VIÊN CỦA PHÒNG NGHIÊN CỨU
   --THÔNG TIN GỒM: MANV, TENNV, DIACHI, LUONG
   DECLARE @BT4 TABLE 
(	MANV	VARCHAR(10), TENNV NVARCHAR(15), DIACHI NVARCHAR(30), LUONG FLOAT)
INSERT INTO @BT4
	SELECT MANV, TENNV, DCHI, LUONG
	FROM NHANVIEN JOIN PHONGBAN ON NHANVIEN.PHG = PHONGBAN.MAPHG
WHERE TENPHG = N'NGHIÊN CỨU'
SELECT * FROM @BT4