IF OBJECT_ID('SPINNT')IS NOT NULL
DROP PROC SPINNT
GO
CREATE PROC SPINNT
@MAND NVARCHAR(10),
@TENND NVARCHAR(50),
@GT NVARCHAR(5),
@DIENTHOAI VARCHAR(15),
@DIACHI NVARCHAR(50),
@QUAN NVARCHAR(30),
@EMAIL VARCHAR(50)
AS
  IF @MAND IS NULL OR @TENND IS NULL OR @GT IS NULL OR @DIENTHOAI IS NULL OR @DIACHI IS NULL OR @QUAN IS NULL OR @EMAIL IS NULL
     PRINT N'DU LIEU NHAP KHONG HOP LE'
  ELSE
     INSERT NGUOIDUNG VALUES(@MAND, @TENND, @GT, @DIENTHOAI, @DIACHI, @QUAN, @EMAIL)

--GOI KHONG THANH CONG
EXEC SPINNT '16', 'HIEUBQ', 'NAM', '0395962002' , NULL, NULL, 'HIEUNQPH13812'

--GOI THANH CONG
EXEC SPINNT '16', 'HIEUBQ', 'NAM', '0395962002' , 'HN', N'?A', 'HIEUNQPH13812'
SELECT * FROM NGUOIDUNG

--2.A SP TÌM KI?M THÔNG TIN NHÀ TR?
IF OBJECT_ID('SPTIMNT')IS NOT NULL
DROP PROC SPTIMNT
GO
CREATE PROC SPTIMNT
   @MAQH NVARCHAR(10), @DTMIN DECIMAL(8,2), @DTMAX DECIMAL(8,2), @NGAYBD DATETIME, @NGAYKT DATETIME, @TIENMIN MONEY, @TIENMAX MONEY, @MALN VARCHAR(10)
AS
  SELECT 
    NHATRO.DIACHI AS DCNT,
	REPLACE(CAST(DIENTICH AS VARCHAR),'.',',') AS DIENTICH,
	REPLACE(CONVERT(VARCHAR, GIAPHONG, 1),',','.') AS GIA,
	MOTA, CONVERT(VARCHAR,NGAYDANGTIN,105) AS NGAYDT,
	CASE
	   WHEN GIOITINH = 'NAM' THEN 'A.' + HOTENND
	   WHEN GIOITINH = N'N?' THEN 'C.' + HOTENND
    END AS NGUOILH,
	SDT,
	NGUOIDUNG.DIACHI AS DCND
	FROM NHATRO JOIN DANHGIA ON NHATRO.MANT = DANHGIA.MANT
	            JOIN NGUOIDUNG ON NGUOIDUNG.MAND = DANHGIA.MAND
    WHERE MAQH = @MAQH
	     AND DIENTICH BETWEEN @DTMIN AND @DTMAX
		 AND NGAYDANGTIN BETWEEN @NGAYBD AND @NGAYKT 
		 AND GIAPHONG BETWEEN @TIENMIN AND @TIENMAX
		 AND MALN = @MALN

--G?I
EXEC SPTIMNT '1',10,50,'1-1-2021','10-10-2021',0, 2500000,'2'
SELECT * FROM QUANHUYEN
SELECT * FROM NHATRO



--2.E. VI?T SP NH?N THAM S? ??U VÀO MÀ MANT
IF OBJECT_ID('SPTTNT')IS NOT NULL
DROP PROC SPTTNT
GO
CREATE PROC SPTTNT
     @MANT VARCHAR(10)
AS
   IF @MANT IS NULL
       PRINT N'D? LI?U KHÔNG H?P L?'
   ELSE 
       SELECT MANT, HOTENND, [LIKE/DISLIKE], NOIDUNG
	   FROM DANHGIA JOIN NGUOIDUNG ON DANHGIA.MAND = NGUOIDUNG.MAND
	   WHERE MANT = @MANT

--G?I KHÔNG THÀNH CÔNG
EXEC SPTTNT NULL

--G?I THÀNH CÔNG
EXEC SPTTNT '113'

/* 3.1 */

IF OBJECT_ID('SPXOANT')IS NOT NULL
DROP PROC SPXOANT
GO
CREATE PROC SPXOANT
    @DIS INT
AS
    BEGIN TRY
	    BEGIN TRAN
		    DECLARE @BANG TABLE
			        (MANT VARCHAR(10), DIS INT)
			   INSERT @BANG SELECT MANT, COUNT([LIKE/DISLIKE]) AS SOLIKE
			                FROM DANHGIA
							WHERE [LIKE/DISLIKE]=0
							GROUP BY MANT
		      DELETE DANHGIA WHERE MANT = (SELECT MANT FROM @BANG WHERE DIS > @DIS)
		COMMIT TRAN
	END TRY
	BEGIN CATCH
	    ROLLBACK TRAN
    END CATCH

EXEC SPXOANT 2


/* 3.2 */

IF OBJECT_ID('SPXOATT')IS NOT NULL
DROP PROC SPXOATT
GO
CREATE PROC SPXOATT
     @NGAYBD DATETIME, @NGAYCUOI DATETIME
AS
BEGIN TRY
	    BEGIN TRAN
		   ---FK
		   DELETE DANHGIA
		   WHERE MANT IN(SELECT MANT FROM NHATRO 
		                                WHERE CONVERT(VARCHAR, NGAYDANGTIN, 105)
										BETWEEN @NGAYBD AND @NGAYCUOI)
           ---PK
		   DELETE NHATRO 
		   WHERE MANT IN(SELECT MANT FROM NHATRO 
		                                WHERE CONVERT(VARCHAR, NGAYDANGTIN, 105)
										BETWEEN @NGAYBD AND @NGAYCUOI)
		COMMIT 
	END TRY
	BEGIN CATCH
	    ROLLBACK TRAN
    END CATCH

	---G?I
	EXEC SPXOATT '2021-01-01','2021-04-07'
	SELECT * FROM NHATRO

	 IF OBJECT_ID('CHKLUONGNV') IS NOT NULL
    DROP TRIGGER CHKLUONGNV
 GO
 CREATE TRIGGER CHKLUONGNV
    ON NHANVIEN FOR INSERT
AS
  IF(SELECT LUONG FROM INSERTED) <15000
     BEGIN 
	    PRINT N'L??NG PH?I L?N H?N 15000'
		ROLLBACK TRAN
	 END
--CHÈN
------CHÈN L?I
INSERT INTO NHANVIEN VALUES ('B','B','B','00','1977','HN','NAM',3000,'005',6)

------CHÈN THÀNH CÔNG
INSERT INTO NHANVIEN VALUES ('B','B','B','00','1977','HN','NAM',30000,'005',6)


SELECT * FROM NHANVIEN
WHERE MANV LIKE '00%'



/*b. Vi?t m?t hàm có các tham s? ??u vào t??ng ?ng v?i t?t c? các c?t c?a b?ng
NGUOIDUNG. Hàm này tr? v? mã ng??i dùng (giá tr? c?a c?t khóa chính c?a b?ng
NGUOIDUNG) th?a mãn các giá tr? ???c truy?n vào tham s?.*/
  
    IF OBJECT_ID('FNND')IS NOT NULL
	  DROP FUNCTION FNND
	GO
	CREATE FUNCTION FNND
	(
	   @TENND NVARCHAR(50), @GIOITINH NVARCHAR(5), @DIENTHOAI VARCHAR(15),
	   @DIACHI NVARCHAR(50), @QUAN NVARCHAR(50), @EMAIL VARCHAR(50)
	)
	RETURNS VARCHAR(10)
	BEGIN 
	  RETURN (SELECT MAND FROM NGUOIDUNG
	          WHERE HOTENND = @TENND
			  AND GIOITINH = @GIOITINH
			  AND SDT = @DIENTHOAI
			  AND DIACHI = @DIACHI
			  AND QUAN = @QUAN
			  AND EMAIL = @EMAIL)
	END
----G?I
DECLARE @MAND VARCHAR(10)
SET @MAND = DBO.FNND(N'Bùi Quang Hi?u',N'Nam','0395962002',N'??i M?ch',N'?ông Anh','hieubq')
SELECT @MAND AS MAND

	SELECT * FROM NGUOIDUNG

/*c. Vi?t m?t hàm có tham s? ??u vào là mã nhà tr? (c?t khóa chính c?a b?ng
NHATRO). Hàm này tr? v? t?ng s? LIKE và DISLIKE c?a nhà tr? này.*/

IF OBJECT_ID('FNTKE')IS NOT NULL
	  DROP FUNCTION FNTKE
GO
CREATE FUNCTION FNTKE
(
   @MANT VARCHAR(10)
)
RETURNS @THONGKE TABLE
       ([LIKE] INT, [DISLIKE] INT)
BEGIN
    ---CÂU L?NH SQL
    --T?NG S? L??NG
	DECLARE @SL INT
	SET @SL = (SELECT COUNT(*) FROM DANHGIA
	           WHERE MANT = @MANT)
	--LIKE HO?C DISLIKE
	DECLARE @LIKE INT
	SET @LIKE = (SELECT COUNT(*) FROM DANHGIA
	           WHERE MANT = @MANT AND [LIKE/DISLIKE] ='1')
	--HI?N TH? RA MÀN HÌNH T?NG LIKE VÀ DISLIKE
	INSERT @THONGKE VALUES (@LIKE, @SL - @LIKE)
	RETURN
END

---DEMO
 SELECT * FROM FNTKE('13')

SELECT * FROM DANHGIA

/*d. T?o m?t View l?u thông tin c?a TOP 10 nhà tr? có s? ng??i dùng LIKE nhi?u nh?t
g?m các thông tin sau:
- Di?n tích
- Giá
- Mô t?
- Ngày ??ng tin
- Tên ng??i liên h?
- ??a ch?
- ?i?n tho?i
- Email
*/
   IF OBJECT_ID('TOP10') IS NOT NULL
       DROP VIEW TOP10
   GO
   CREATE VIEW TOP10
   AS
     SELECT TOP 3 DIENTICH, GIAPHONG, MOTA, NGAYDANGTIN, HOTENND, NGUOIDUNG.DIACHI, 
	 SDT, EMAIL, COUNT([LIKE/DISLIKE]) AS LIKEMAX
	 FROM NHATRO JOIN DANHGIA ON NHATRO.MANT = DANHGIA.MANT
	             JOIN NGUOIDUNG ON NGUOIDUNG.MAND = DANHGIA.MAND
		WHERE [LIKE/DISLIKE]=1
	GROUP BY DIENTICH, GIAPHONG, MOTA, NGAYDANGTIN, HOTENND, NGUOIDUNG.DIACHI, 
	 SDT, EMAIL
	ORDER BY LIKEMAX DESC
	---G?I
	SELECT * FROM TOP10